[package]
name = "voyager-host"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
bluer = { version = "0.17.4", features = ["bluetoothd"] }
futures = "0.3.32"
tokio = { version = "1.49.0", features = ["full"] }
uuid = "1.21.0"
