[package]
name = "voyager-display"
version = "0.1.0"
edition = "2024"

[dependencies]
font_generator = { version = "0.1.0", path = "../font-generator", default-features = false }
embedded-graphics = { version = "0.8.1", default-features = false }
heapless = "0.9"

[features]
default = []
std = []
