[package]
edition = "2024"
name = "voyager"
version = "0.1.0"

[dependencies]
cortex-m = { version = "0.7.7", features = ["inline-asm"] }
cortex-m-rt = "0.7.5"
defmt = { version = "1.0.1", optional = true }
defmt-rtt = { version = "1.1.0", optional = true }
embassy-executor = { version = "0.9.1", features = ["arch-cortex-m", "executor-thread", "executor-interrupt"] }
embassy-futures = "0.1.2"
embassy-nrf = { version = "0.9.0", features = ["nrf52840", "gpiote", "time-driver-rtc1", "unstable-pac", "rt"] }
embassy-sync = "0.7.2"
embassy-time = { version = "0.5.0", features = ["tick-hz-32_768"] }
embedded-graphics = "0.8.1"
panic-halt = "1.0.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"], optional = true }
ssd1306 = { version = "0.10.0", features = ["async", "graphics"], default-features = false }
static_cell = "2.1.1"

# BLE dependencies
nrf-sdc = { git = "https://github.com/alexmoon/nrf-sdc.git", default-features = false, features = ["peripheral", "nrf52840"] }
nrf-mpsl = { git = "https://github.com/alexmoon/nrf-sdc.git", default-features = false, features = ["critical-section-impl", "nrf52840"] }
bt-hci = { version = "0.7", default-features = false }
trouble-host = { git = "https://github.com/embassy-rs/trouble.git", default-features = false, features = ["peripheral", "gatt", "derive", "default-packet-pool"] }
portable-atomic = { version = "1.10", features = ["critical-section"] }
rand = { version = "0.8", default-features = false }
rand_core = "0.9"
futures = { version = "0.3", default-features = false, features = ["async-await"] }
heapless = "0.9"
chrono = { version = "0.4.42", default-features = false }

[patch.crates-io]
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-nrf = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-time-driver = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-hal-internal = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy.git" }
embassy-usb-driver = { git = "https://github.com/embassy-rs/embassy.git" }

[[bin]]
name = "voyager"
test = false
bench = false

[profile.dev]
debug = true
lto = true
opt-level = "z"
incremental = true

[profile.release]
debug = 2
lto = true
opt-level = "z"
incremental = true

[features]
defmt = ["dep:defmt"]
defmt-rtt = ["dep:defmt-rtt"]
panic-probe = ["dep:panic-probe"]
default = ["debug"]
debug = [
    "defmt",
    "defmt-rtt",
    "panic-probe",
    "embassy-executor/defmt",
    "embassy-sync/defmt",
    "embassy-futures/defmt",
    "embassy-time/defmt",
    "embassy-time/defmt-timestamp-uptime",
    "embassy-nrf/defmt",
    "nrf-sdc/defmt",
    "nrf-mpsl/defmt",
    "bt-hci/defmt",
    "trouble-host/defmt",
]
