name: 'firmware'

on: [push, pull_request]

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firmware

    steps:
      - uses: actions/checkout@v4

      - name: install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '1.90'
          targets: thumbv7em-none-eabihf
          components: rustfmt, clippy

      - name: run format check
        run: cargo fmt --check

      - name: run clippy
        run: cargo clippy -- -D warnings

      - name: build
        run: cargo build --release
